version: '3'

services:
  server:
    build:
      context: server
      dockerfile: Dockerfile
    container_name: server
    command: sleep infinity

  client:
    build:
      context: client
      dockerfile: Dockerfile
    container_name: client
    command: sleep infinity
